src/AppBundle/Entity/City.php
<?php
/**
 * Created by PhpStorm.
 * User: pix
 * Date: 13.04.17
 * Time: 12:10
 */

namespace AppBundle\Entity;


use AppBundle\VO\ExternalRouter;
use AppBundle\VO\LanguageString;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Config\Definition\Exception\Exception;

/**
 * @ORM\Entity(repositoryClass="AppBundle\Repository\CityRepository")
 * @ORM\Table(name="cities")
 */
class City
{
	/**
	 * @var int
	 * @ORM\Id()
	 * @ORM\Column(name="city_id", type="integer")
	 * @ORM\GeneratedValue(strategy="AUTO")
	 */
	private $id;

	/**
	 * @var LanguageString
	 * @ORM\Column(name="name", type="object", nullable=false)
	 */
	private $name;

	/**
	 * @var LanguageString
	 * @ORM\Column(name="next_variations", type="string", nullable=false)
	 */
	private $nextVariations = "";

	/**
	 * @var Country
	 * @ORM\ManyToOne(targetEntity="Country", inversedBy="cities")
	 * @ORM\JoinColumn(name="country_id", referencedColumnName="country_id", nullable=false)
	 */
	private $country;

	/**
	 * @var Station[]|ArrayCollection
	 * @ORM\OneToMany(targetEntity="Station", mappedBy="city")
	 */
	private $stations;

	/**
	 * @var ExternalCity[]|ArrayCollection
	 * @ORM\OneToMany(targetEntity="ExternalCity", mappedBy="city")
	 */
	private $externalCities;

	/**
	 * @var boolean
	 * @ORM\Column(name="deleted", type="boolean", nullable=false)
	 */
	private $deleted = false;

	public function __construct()
	{
		$this->name = new LanguageString;
		$this->stations = new ArrayCollection;
	}

	/**
	 * @return int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * @param int $id
	 */
	public function setId($id)
	{
		$this->id = $id;
	}

	/**
	 * @return LanguageString
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * @param Language $language
	 * @param string $name
	 */
	public function setName(Language $language, $name)
	{
		$this->name = clone $this->getName()->setString($language, $name);
	}

	/**
	 * @return Country
	 */
	public function getCountry()
	{
		return $this->country;
	}

	/**
	 * @param Country $country
	 */
	public function setCountry($country)
	{
		$this->country = $country;
	}

	/**
	 * @return \string[]
	 */
	public function getAllLanguagesNames()
	{
		return $this->getName()->getAllLanguagesStrings();
	}

	/**
	 * @return Station[]|ArrayCollection
	 */
	public function getStations()
	{
		return $this->stations;
	}

	/**
	 * @param Station[]|ArrayCollection $stations
	 */
	public function setStations($stations)
	{
		$this->stations = $stations;
	}

	/**
	 * @return ExternalCity[]|ArrayCollection
	 */
	public function getExternalCities()
	{
		return $this->externalCities;
	}

	/**
	 * @param ExternalCity[]|ArrayCollection $externalCities
	 */
	public function setExternalCities($externalCities)
	{
		$this->externalCities = $externalCities;
	}

	/**
	 * @param string $type
	 * @return ExternalCity|null
	 */
	public function getExternalCity($type)
	{
		return !$this->getExternalCitiesByType($type)->isEmpty() ? $this->getExternalCitiesByType($type)->first() : null;
	}

	/**
	 * @param string $type
	 * @return ExternalCity[]|ArrayCollection
	 */
	public function getExternalCitiesByType($type)
	{
		return $this->getExternalCities()->filter(function ($externalCity) use ($type) {
			if ($type == ExternalRouter::STUDENT_AGENCY and $externalCity instanceof ExternalCityStudentAgency) {
				return true;
			} elseif ($type == ExternalRouter::ECOLINES and $externalCity instanceof ExternalCityEcolines) {
				return true;
			} elseif ($type == ExternalRouter::INFOBUS and $externalCity instanceof ExternalCityInfobus) {
				return true;
			} elseif ($type == ExternalRouter::EAST_EXPRESS and $externalCity instanceof ExternalCityEastExpress) {
				return true;
			} elseif ($type == ExternalRouter::FLIXBUS and $externalCity instanceof ExternalCityFlixbus) {
				return true;
			} elseif ($type == ExternalRouter::NIKOLO and $externalCity instanceof ExternalCityNikoloBusSystem) {
				return true;
			} elseif ($type == ExternalRouter::EUROLINES and $externalCity instanceof ExternalCityEurolines) {
				return true;
			} elseif ($type == ExternalRouter::REGABUS and $externalCity instanceof ExternalCityRegabus) {
				return true;
			} elseif ($type == ExternalRouter::BLABLA and $externalCity instanceof ExternalCityBlabla) {
				return true;
			} elseif ($type == ExternalRouter::TRANS_TEMPO and $externalCity instanceof ExternalCityTransTempo) {
				return true;
			} elseif ($type == ExternalRouter::LIKEBUS and $externalCity instanceof ExternalCityLikeBus) {
				return true;
			}

			return false;
		});
	}

	/**
	 * @return LanguageString
	 */
	public function getNextVariations()
	{
		return $this->nextVariations;
	}

	/**
	 * @param LanguageString $nextVariations
	 */
	public function setNextVariations($nextVariations)
	{
		$this->nextVariations = $nextVariations;
	}

	/**
	 * @return bool
	 */
	public function isDeleted(): bool
	{
		return $this->deleted;
	}

	/**
	 * @param bool $deleted
	 */
	public function setDeleted(bool $deleted)
	{
		$this->deleted = $deleted;
	}

}

src/AppBundle/Entity/Country.php
<?php
/**
 * Created by PhpStorm.
 * User: pix
 * Date: 13.04.17
 * Time: 12:13
 */

namespace AppBundle\Entity;


use AppBundle\VO\LanguageString;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="AppBundle\Repository\CountryRepository")
 * @ORM\Table(name="countries")
 */
class Country
{
	/**
	 * @var int
	 * @ORM\Id()
	 * @ORM\Column(name="country_id", type="integer")
	 * @ORM\GeneratedValue(strategy="AUTO")
	 */
	private $id;

	/**
	 * @var LanguageString
	 * @ORM\Column(name="name", type="object", nullable=false)
	 */
	private $name;

	/**
	 * @var City[]|ArrayCollection
	 * @ORM\OneToMany(targetEntity="City", mappedBy="country")
	 */
	private $cities;

	public function __construct()
	{
		$this->name = new LanguageString;
		$this->cities = new ArrayCollection;
	}

	/**
	 * @return int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * @param int $id
	 */
	public function setId($id)
	{
		$this->id = $id;
	}

	/**
	 * @return LanguageString
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * @param Language $language
	 * @param string $name
	 */
	public function setName(Language $language, $name)
	{
		$this->name = clone $this->getName()->setString($language, $name);
	}

	/**
	 * @return City[]|ArrayCollection
	 */
	public function getCities()
	{
		return $this->cities;
	}

	/**
	 * @return City[]|ArrayCollection
	 */
	public function getActiveCities()
	{
		return $this->getCities()->filter(function (City $city) {
			return !$city->isDeleted();
		});
	}

	/**
	 * @return City[]
	 */
	public function getActiveCitiesSortByName()
	{
		$cities = $this->getCities()->filter(function (City $city) {
			return !$city->isDeleted();
		})->toArray();

		usort($cities, function (City $a, City $b) {
			return strcmp($a->getName()->getAllLanguagesStringsInString(), $b->getName()->getAllLanguagesStringsInString());
		});

		return $cities;
	}

	/**
	 * @param City[]|ArrayCollection $cities
	 */
	public function setCities($cities)
	{
		$this->cities = $cities;
	}

}

src/AppBundle/Controller/Backend/CarrierController.php
<?php
/**
 * Created by PhpStorm.
 * User: pix
 * Date: 31.10.17
 * Time: 14:18
 */

namespace AppBundle\Controller\Backend;
use AppBundle\Entity\Carrier;
use AppBundle\Service\CarrierService;
use AppBundle\Widget\Backend\MenuWidget;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Routing\Router;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;

/**
 * @Route(service="controller.backend.carrier")
 * @Security("has_role('ROLE_SUPER_ADMIN')")
 */
class CarrierController
{
	const PARAM_CODE = "code";
	const PARAM_NAME = "name";
	const PARAM_SURCHARGE = "surcharge";
	const PARAM_COMMISSION = "commission";
	const PARAM_VALUE = "value";
	const PARAM_CANT_PAY_ONLINE = "cantPayOnline";

	/**
	 * @var CarrierService
	 */
	private $carrierService;
	/**
	 * @var Router
	 */
	private $router;
	/**
	 * @var MenuWidget
	 */
	private $menuWidget;
	/**
	 * @var \AppBundle\Service\FlashService
	 */
	private $flashService;

	public function __construct(CarrierService $carrierService,
	                            Router $router,
	                            MenuWidget $menuWidget,
	                            \AppBundle\Service\FlashService $flashService)
	{
		$this->carrierService = $carrierService;
		$this->router = $router;
		$this->menuWidget = $menuWidget;
		$this->flashService = $flashService;

		$this->menuWidget->setActive(MenuWidget::ACTIVE_CARRIERS);
	}

	/**
	 * @Route(path="/backend/carriers", name="backend_carriers", methods={"GET"})
	 * @Template()
	 */
	public function carriersAction()
	{
		return [
			"carriers" => $this->carrierService->findAllCarriers(),
			"deletedCarriers" => $this->carrierService->findAllDeletedCarriers()
		];
	}

	/**
	 * @Route(path="/backend/carrier/create", name="backend_carrier_create", methods={"POST"})
	 * @param Request $request
	 * @return RedirectResponse
	 */
	public function carrierCreateAction(Request $request)
	{
		$code = $request->request->get(self::PARAM_CODE);
		
		if ($this->carrierService->existsCarrierWithCode($code)) {
			$this->flashService->addError(sprintf('Dopravce s kódem %s již existuje', $code));
			return RedirectResponse::create($this->router->generate("backend_carriers"));
		}
		
		$carrier = new Carrier;
		$carrier->setCode($code);
		$carrier->setName($request->request->get(self::PARAM_NAME));
		$this->carrierService->saveCarrier($carrier);

		return RedirectResponse::create($this->router->generate("backend_carriers"));
	}

	/**
	 * @Route(path="/backend/carrier/{carrier}", name="backend_carrier_save", methods={"POST"})
	 * @param Carrier $carrier
	 * @return RedirectResponse
	 */
	public function carrierSaveAction(Carrier $carrier, Request $request)
	{
		$surcharge = $request->request->getInt(self::PARAM_SURCHARGE);
		$commission = $request->request->getInt(self::PARAM_COMMISSION);
		$cantPayOnline = $request->request->get(self::PARAM_CANT_PAY_ONLINE) === "on";

		$carrier->setSurcharge($surcharge > 0 ? $surcharge : null);
		$carrier->setCommission($commission > 0 ? $commission : null);
		$carrier->setCantPayOnline($cantPayOnline);
		$this->carrierService->saveCarrier($carrier);

		return RedirectResponse::create($this->router->generate("backend_carriers"));
	}

	/**
	 * @Route(path="/backend/_ajax/carrier/{carrier}/changeName", name="backend_ajax_carrier_change_name", methods={"POST"})
	 * @param Carrier $carrier
	 * @return JsonResponse
	 */
	public function ajaxCarrierChangeNameAction(Carrier $carrier, Request $request)
	{
		$carrier->setName($request->request->get(self::PARAM_VALUE));
		$this->carrierService->saveCarrier($carrier);

		return JsonResponse::create();
	}

	/**
	 * @Route(path="/backend/carrier/{carrier}/remove", name="backend_carrier_remove", methods={"POST"})
	 * @param Carrier $carrier
	 * @return RedirectResponse
	 */
	public function carrierRemoveAction(Carrier $carrier)
	{
		$carrier->setDeleted(true);
		$this->carrierService->saveCarrier($carrier);

		return RedirectResponse::create($this->router->generate("backend_carriers"));
	}
	
	/**
	 * @Route(path="/backend/carrier/{carrier}/restore", name="backend_carrier_restore", methods={"POST"})
	 * @param Carrier $carrier
	 * @return RedirectResponse
	 */
	public function carrierRestoreAction(Carrier $carrier)
	{
		$carrier->setDeleted(false);
		$this->carrierService->saveCarrier($carrier);

		return RedirectResponse::create($this->router->generate("backend_carriers"));
	}

}

src/AppBundle/Controller/Backend/CityController.php
<?php
/**
 * Created by PhpStorm.
 * User: pix
 * Date: 07.07.17
 * Time: 16:16
 */

namespace AppBundle\Controller\Backend;


use AppBundle\Entity\City;
use AppBundle\Service\CityService;
use AppBundle\Service\CountryService;
use AppBundle\Service\LanguageService;
use AppBundle\Service\LineService;
use AppBundle\Widget\Backend\MenuWidget;
use Doctrine\ORM\Mapping as ORM;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Routing\Router;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;

/**
 * @Route(service="controller.backend.city")
 * @Security("has_role('ROLE_SUPER_ADMIN')")
 */
class CityController
{
	const PARAM_LANGUAGE = "language";
	const PARAM_VALUE = "value";
	const PARAM_COUNTRY = "country";
	const PARAM_NAME = "name";

	/**
	 * @var CityService
	 */
	private $cityService;
	/**
	 * @var LanguageService
	 */
	private $languageService;
	/**
	 * @var CountryService
	 */
	private $countryService;
	/**
	 * @var MenuWidget
	 */
	private $menuWidget;
	/**
	 * @var LineService
	 */
	private $lineService;
	/**
	 * @var Router
	 */
	private $router;

	public function __construct(CityService $cityService,
	                            LanguageService $languageService,
	                            CountryService $countryService,
	                            MenuWidget $menuWidget,
	                            LineService $lineService,
	                            Router $router)
	{
		$this->cityService = $cityService;
		$this->languageService = $languageService;
		$this->countryService = $countryService;
		$this->menuWidget = $menuWidget;
		$this->lineService = $lineService;
		$this->router = $router;

		$this->menuWidget->setActive(MenuWidget::ACTIVE_CITIES);
	}

	/**
	 * @Route(path="/backend/cities", name="backend_cities")
	 * @Template()
	 * @return array
	 */
	public function citiesAction(Request $request)
	{
		if ($request->query->has(self::PARAM_COUNTRY)) {
			$country = $this->countryService->getCountry($request->query->get(self::PARAM_COUNTRY));
		} else {
			$country = null;
		}

		return [
			"countries" => $this->countryService->findAllCountries(),
			"englishLanguage" => $this->languageService->getEnglish(),
			"czechLanguage" => $this->languageService->getCzech(),
			"russianLanguage" => $this->languageService->getRussian(),
			"ukrainianLanguage" => $this->languageService->getUkrainian(),
			"bulgarianLanguage" => $this->languageService->getBulgarion(),
			"country" => $country,
			"lines" => $this->lineService->getAllLines()
		];
	}

	/**
	 * @Route(path="/backend/cities/add", name="backend_cities_add", methods={"GET"})
	 * @Template()
	 * @return array
	 */
	public function cityAddAction()
	{
		return [
			"countries" => $this->countryService->findAllCountries()
		];
	}

	/**
	 * @Route(path="/backend/cities/add", name="backend_cities_add_save", methods={"POST"})
	 * @param Request $request
	 * @return RedirectResponse
	 */
	public function cityAddSaveAction(Request $request)
	{
		$city = new City();
		foreach ($request->request->get(self::PARAM_NAME) as $lng => $name) {
			$city->setName($this->languageService->getLanguage($lng), $name);
		}
		$city->setCountry($this->countryService->getCountry($request->request->get(self::PARAM_COUNTRY)));
		$this->cityService->saveCity($city);

		return RedirectResponse::create($this->router->generate("backend_cities"));
	}

	/**
	 * @Route(path="/backend/_ajax/city/{city}", name="ajax_backend_city_save", methods={"POST"})
	 * @return JsonResponse
	 */
	public function ajaxCitySaveAction(City $city, Request $request)
	{
		if ($request->request->has(self::PARAM_LANGUAGE) and $request->request->has(self::PARAM_VALUE)) {
			$lng = $request->request->get(self::PARAM_LANGUAGE);
			$value = $request->request->get(self::PARAM_VALUE);

			if ($lng == "nextVariations") {
				$city->setNextVariations($value);
			} else {
				$city->setName(
					$this->languageService->getLanguage($lng),
					$request->request->get(self::PARAM_VALUE)
				);
			}

			$this->cityService->saveCity($city);
		}

		return JsonResponse::create();
	}

	/**
	 * @Route(path="/backend/city/{city}/remove", name="ajax_backend_city_remove", methods={"POST"})
	 * @return RedirectResponse
	 */
	public function cityRemoveAction(City $city, Request $request)
	{
		$city->setDeleted(true);
		$this->cityService->saveCity($city);

		return RedirectResponse::create($this->router->generate("backend_cities"));
	}
}

src/AppBundle/Controller/Backend/HomepageController.php
<?php
/**
 * Created by PhpStorm.
 * User: pix
 * Date: 28.06.17
 * Time: 22:57
 */

namespace AppBundle\Controller\Backend;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;

/**
 * @Route(service="")
 */
class HomepageController
{
	/**
	 * @Route(path="/backend", name="backend_homepage", methods={"GET"})
	 * @Template()
	 * @return array
	 */
	public function homepageAction()
	{
		return [

		];
	}
}

src/AppBundle/Resources/views/Backend/External/cities.html.twig
{% extends 'AppBundle:Backend/Layout:Skeleton.html.twig' %}

{% block content %}

	<div class="container">
		<div class="row">
			<div class="col-md-12">
			{% for c in countries %}
				<h3>{{ c.name|language }}</h3>
				<table class="table table-striped table-hover table-external-cities table-bordered">
					<thead>
					<tr>
						<th>Město</th>
						<th>East Express</th>
						<th>Ecolines</th>
						<th>Flixbus</th>
						<th>Infobus</th>
						<th>RegioJet</th>
						<th>Eurolines</th>
						<th>Nikolo</th>
                        <th>Blabla</th>
						<th>TransTempo</th>
                        <th>LikeBus</th>
					</tr>
					</thead>
					<tbody>
					{% for city in c.activeCitiesSortByName %}
						<tr data-url="{{ path("backend_externals_city_set_external", { city: city.id }) }}">
							<td>
								<strong>{{ city.name|language }}</strong>
							</td>
							<td data-carrier="east_express">
								{% if city.externalCity("east_express") %}
									{{ city.externalCity("east_express").name|language }}
								{% endif %}
							</td>
							<td data-carrier="ecolines">
								{% if city.externalCity("ecolines") %}
									{{ city.externalCity("ecolines").name|language }}
								{% endif %}
							</td>
							<td data-carrier="flixbus">
								{% if city.externalCity("flixbus") %}
									{{ city.externalCity("flixbus").name|language }}
								{% endif %}
							</td>
							<td data-carrier="infobus">
								{% if city.externalCity("infobus") %}
									{{ city.externalCity("infobus").name|language }}
								{% endif %}
							</td>
							<td data-carrier="student_agency">
								{% if city.externalCity("student_agency") %}
									{{ city.externalCity("student_agency").name|language }}
								{% endif %}
							</td>
							<td data-carrier="eurolines">
								{% if city.externalCity("eurolines") %}
									{{ city.externalCity("eurolines").name|language }}
								{% endif %}
							</td>
							<td data-carrier="nikolo">
								{% for ec in city.externalCitiesByType("nikolo") %}
									{{ ec.name|language }}{% if not loop.last %},<br>{% endif %}
								{% endfor %}
							</td>
                            <td data-carrier="blabla">
                                {% if city.externalCity("blabla") %}
                                    {{ city.externalCity("blabla").name|language }}
                                {% endif %}
                            </td>
							<td data-carrier="trans_tempo">
								{% if city.externalCity("trans_tempo") %}
									{{ city.externalCity("trans_tempo").name|language }}
								{% endif %}
							</td>
                            <td data-carrier="likebus">
                                {% if city.externalCity("likebus") %}
                                    {{ city.externalCity("likebus").name|language }}
                                {% endif %}
                            </td>
						</tr>
					{% endfor %}
					</tbody>
				</table>
			{% endfor %}
			</div>
		</div>
	</div>

{% endblock %}

src/AppBundle/Resources/views/Backend/External/citiesApprove.html.twig
{% extends 'AppBundle:Backend/Layout:Skeleton.html.twig' %}

{% block content %}

	<div class="container">
		<form action="{{ path("backend_externals_cities_save") }}" method="post">
			<div class="row">
				<div class="col-md-12">
					<table class="table table-striped">
						<thead>
						<tr>
							<th>Dopravce</th>
							<th>Externí město</th>
							<th>Interní město</th>
						</tr>
						</thead>
						<tbody>
						{% for externalCity in externalCities|slice(0, 5) %}
							<tr>
								<td>
									{% if externalCity is externalCityEastExpress %}
										EastExpress
									{% elseif externalCity is externalCityEcolines %}
										Ecolines
									{% elseif externalCity is externalCityEurolines %}
										Eurolines
									{% elseif externalCity is externalCityFlixbus %}
										Flixbus
									{% elseif externalCity is externalCityInfobus %}
										Infobus
									{% elseif externalCity is externalCityNikolo %}
										Nikolo
									{% elseif externalCity is externalCityStudentAgency %}
										StudentAgency
									{% elseif externalCity is externalCityRegabus %}
										Regabus
									{% endif %}
								</td>
								<td>
									{{ externalCity.name|language }}
								</td>
								<td>
									<select name="cities[{{ externalCity.id }}]" class="selectpicker" data-live-search="true">
										<option value="" style="color: silver;">Zvolte odpovídající město</option>
										{% for city in cities %}
											<option data-tokens="{{ city.allLanguagesNames|join(" ") }}" value="{{ city.id }}"{% if externalCity.city == city %} selected{% endif %}>{{ city.name|language }}</option>
										{% endfor %}
									</select>
								</td>
							</tr>
						{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<button type="submit" class="btn btn-success">Uložit</button>
				</div>
			</div>
		</form>
	</div>

{% endblock %}