src/AppBundle/Entity/Schedule.php
<?php
/**
 * Created by PhpStorm.
 * User: pix
 * Date: 13.04.17
 * Time: 15:01
 */

namespace AppBundle\Entity;


use AppBundle\VO\DayRange;
use AppBundle\VO\Days;
use AppBundle\VO\LanguageString;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="AppBundle\Repository\ScheduleRepository")
 * @ORM\Table(name="schedules")
 */
class Schedule
{
	/**
	 * @var int
	 * @ORM\Id()
	 * @ORM\Column(name="schedule_id", type="integer")
	 * @ORM\GeneratedValue(strategy="AUTO")
	 */
	private $id;

	/**
	 * @var Line
	 * @ORM\ManyToOne(targetEntity="Line", inversedBy="schedules")
	 * @ORM\JoinColumn(name="line_id", referencedColumnName="line_id", nullable=false)
	 */
	private $line;

	/**
	 * @var int[]|ArrayCollection
	 * @ORM\Column(name="week_days", type="array", nullable=false)
	 */
	private $weekDays;

	/**
	 * @var Days
	 * @ORM\Column(name="include_days", type="object", nullable=false)
	 */
	private $includeDays;

	/**
	 * @var Days
	 * @ORM\Column(name="exclude_days", type="object", nullable=false)
	 */
	private $excludeDays;

	/**
	 * @var ScheduleLineStation[]|ArrayCollection
	 * @ORM\OneToMany(targetEntity="ScheduleLineStation", mappedBy="schedule", cascade={"all"})
	 */
	private $scheduleLineStations;

	/**
	 * @var string
	 * @ORM\Column(name="direction", type="string", length=32, nullable=false)
	 */
	private $direction;

	/**
	 * @var int
	 * @ORM\Column(name="old_price_table_number", type="integer", nullable=true)
	 */
	private $oldPriceTableNumber;

	/**
	 * @var Tariff
	 * @ORM\ManyToOne(targetEntity="Tariff")
	 * @ORM\JoinColumn(name="tariff_id", referencedColumnName="tariff_id", nullable=true)
	 */
	private $tariff;

	/**
	 * @var Tariff[]|ArrayCollection
	 * @ORM\ManyToMany(targetEntity="Tariff", cascade={"persist"})
	 * @ORM\JoinTable(
	 *     name="schedules_tariffs",
	 *     joinColumns={@ORM\JoinColumn(name="schedule_id", referencedColumnName="schedule_id")},
	 *     inverseJoinColumns={@ORM\JoinColumn(name="tariff_id", referencedColumnName="tariff_id")}
	 * )
	 */
	private $tariffs;

	/**
	 * @var int
	 * @ORM\Column(name="own_seats", type="integer", nullable=true)
	 */
	private $ownSeats;

	/**
	 * @var boolean
	 * @ORM\Column(name="deleted", type="boolean", nullable=false)
	 */
	private $deleted = false;

	/**
	 * @var int
	 * @ORM\Column(name="weight", type="smallint", nullable=false)
	 */
	private $weight = 0;

	/**
	 * @var LanguageString
	 * @ORM\Column(name="private_note", type="object", nullable=false)
	 */
	private $privateNote;

	/**
	 * @var LanguageString
	 * @ORM\Column(name="public_note", type="object", nullable=false)
	 */
	private $publicNote;

	/**
	 * @var bool
	 * @ORM\Column(name="seats_without_numbers", type="boolean", nullable=false)
	 */
	private $seatsWithoutNumbers = false;

	/**
	 * @var bool
	 * @ORM\Column(name="pay_online_disabled", type="boolean", nullable=false)
	 */
	private $payOnlineDisabled = false;

	public function __construct()
	{
		$this->weekDays = new ArrayCollection;
		$this->scheduleLineStations = new ArrayCollection;
		$this->tariffs = new ArrayCollection;
		$this->includeDays = new Days;
		$this->includeDays->setAll(true);
		$this->excludeDays = new Days;
	}

	/**
	 * @return int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * @param int $id
	 */
	public function setId($id)
	{
		$this->id = $id;
	}

	/**
	 * @return Line
	 */
	public function getLine()
	{
		return $this->line;
	}

	/**
	 * @param Line $line
	 */
	public function setLine($line)
	{
		$this->line = $line;
	}

	/**
	 * @return ArrayCollection|\int[]
	 */
	public function getWeekDays()
	{
		if ($this->weekDays instanceof ArrayCollection) {
			return $this->weekDays;
		} else {
			return new ArrayCollection($this->weekDays);
		}
	}

	/**
	 * @param int $day
	 */
	public function addWeekDay($day)
	{
		if (!$this->getWeekDays()->contains($day)) {
			$this->getWeekDays()->add($day);
		}
	}

	/**
	 * @param ArrayCollection|\int[] $weekDays
	 */
	public function setWeekDays($weekDays)
	{
		$this->weekDays = $weekDays;
	}

	/**
	 * @return Days
	 */
	public function getExcludeDays()
	{
		return $this->excludeDays;
	}

	/**
	 * @param Days $excludeDays
	 */
	public function setExcludeDays($excludeDays)
	{
		$this->excludeDays = $excludeDays;
	}

	/**
	 * @return Days
	 */
	public function getIncludeDays()
	{
		return $this->includeDays;
	}

	/**
	 * @param Days $includeDays
	 */
	public function setIncludeDays($includeDays)
	{
		$this->includeDays = $includeDays;
	}

	/**
	 * @return ScheduleLineStation[]|ArrayCollection
	 */
	public function getScheduleLineStations()
	{
		return $this->scheduleLineStations;
	}

	/**
	 * @return ScheduleLineStation[]|ArrayCollection
	 */
	public function getActiveScheduleLineStations()
	{
		return $this->scheduleLineStations->filter(function (ScheduleLineStation $sls) {
			return !$sls->isDeleted();
		});
	}

	/**
	 * @param ScheduleLineStation[]|ArrayCollection $scheduleLineStations
	 */
	public function setScheduleLineStations($scheduleLineStations)
	{
		$this->scheduleLineStations = $scheduleLineStations;
	}

	/**
	 * @param ScheduleLineStation $scheduleLineStation
	 */
	public function addScheduleLineStation(ScheduleLineStation $scheduleLineStation)
	{
		$this->scheduleLineStations->add($scheduleLineStation);
		$scheduleLineStation->setSchedule($this);
	}

	/**
	 * @param City $city
	 * @return ScheduleLineStation|null
	 */
	public function getScheduleLineStationForCity(City $city)
	{
		/** @var ArrayCollection|ScheduleLineStation[] $return */
		$return = $this->getActiveScheduleLineStations()->filter(function (ScheduleLineStation $scheduleLineStation) use ($city) {
			return $scheduleLineStation->getLineStation()->getCity() == $city;
		});

		return $return->isEmpty() ? null : $return->first();
	}

	/**
	 * @param City $city
	 * @return ScheduleLineStation[]|ArrayCollection|null
	 */
	public function getScheduleLineStationsForCity(City $city)
	{
		/** @var ArrayCollection|ScheduleLineStation[] $return */
		$return = $this->getActiveScheduleLineStations()->filter(function (ScheduleLineStation $scheduleLineStation) use ($city) {
			return $scheduleLineStation->getLineStation()->getCity() === $city;
		});

		return $return;
	}

	/**
	 * @param LineStation $lineStation
	 * @return ScheduleLineStation|null
	 */
	public function getScheduleLineStationsForLineStation(LineStation $lineStation)
	{
		/** @var ArrayCollection|ScheduleLineStation[] $return */
		$return = $this->getActiveScheduleLineStations()->filter(function (ScheduleLineStation $scheduleLineStation) use ($lineStation) {
			return $scheduleLineStation->getLineStation() === $lineStation;
		});

		return $return->isEmpty() ? null : $return->first();
	}

	/**
	 * @return string
	 */
	public function getDirection()
	{
		return $this->direction;
	}

	/**
	 * @param string $direction
	 */
	public function setDirection($direction)
	{
		$this->direction = $direction;
	}

	/**
	 * @return int
	 */
	public function getOldPriceTableNumber()
	{
		return $this->oldPriceTableNumber;
	}

	/**
	 * @param int $oldPriceTableNumber
	 */
	public function setOldPriceTableNumber($oldPriceTableNumber)
	{
		$this->oldPriceTableNumber = $oldPriceTableNumber;
	}

	/**
	 * @return Tariff
	 * @deprecated
	 */
	public function getTariff()
	{
		return $this->tariff;
	}

	/**
	 * @param Tariff $tariff
	 * @deprecated
	 */
	public function setTariff($tariff)
	{
		$this->tariff = $tariff;
	}

	/**
	 * @return Tariff[]|ArrayCollection
	 */
	public function getTariffs()
	{
		return $this->tariffs;
	}

	/**
	 * @return Tariff[]|ArrayCollection
	 */
	public function getActiveTariffs()
	{
		return $this->tariffs->filter(function (Tariff $tariff) {
			return !$tariff->isDeleted();
		});
	}

	/**
	 * @param Tariff[]|ArrayCollection $tariffs
	 */
	public function setTariffs($tariffs)
	{
		$this->tariffs = $tariffs;
	}

	/**
	 * @return int
	 */
	public function getOwnSeats()
	{
		return $this->ownSeats;
	}

	/**
	 * @param int $ownSeats
	 */
	public function setOwnSeats($ownSeats)
	{
		$this->ownSeats = $ownSeats;
	}

	/**
	 * @return boolean
	 */
	public function isDeleted()
	{
		return $this->deleted;
	}

	/**
	 * @param boolean $deleted
	 */
	public function setDeleted($deleted)
	{
		$this->deleted = $deleted;
	}

	function __clone()
	{
		$this->setId(null);
	}

	/**
	 * @return int
	 */
	public function getWeight()
	{
		return $this->weight;
	}

	/**
	 * @param int $weight
	 */
	public function setWeight($weight)
	{
		$this->weight = $weight;
	}

	/**
	 * @param string $direction
	 * @return ScheduleLineStation|null
	 */
	public function getFirstScheduleLineStation()
	{
		/** @var ScheduleLineStation $return */
		$return = null;

		$this->getLine()->getLineStations($this->getDirection())->map(function (LineStation $lineStation) use (&$return) {
			$scheduleLineStation = $this->getScheduleLineStationsForLineStation($lineStation);
			if ($scheduleLineStation and $scheduleLineStation->getTime()->getDepartureTime()) {
				if ($return === null) $return = $scheduleLineStation;
			}
		});

		return $return;
	}

	/**
	 * @param string $direction
	 * @return ScheduleLineStation|null
	 */
	public function getLastScheduleLineStation()
	{
		/** @var ScheduleLineStation $return */
		$return = null;

		$this->getLine()->getLineStations($this->getDirection())->map(function (LineStation $lineStation) use (&$return) {
			$scheduleLineStation = $this->getScheduleLineStationsForLineStation($lineStation);
			if ($scheduleLineStation and $scheduleLineStation->getTime()->getDepartureTime()) {
				$return = $scheduleLineStation;
			}
		});

		return $return;
	}

	/**
	 * @return LanguageString
	 */
	public function getPrivateNote()
	{
		return $this->privateNote;
	}

	/**
	 * @param Language $language
	 * @param string $privateNote
	 */
	public function setPrivateNote(Language $language, $privateNote)
	{

src/AppBundle/Entity/SeatsPlan.php
<?php
/**
 * Created by PhpStorm.
 * User: pix
 * Date: 15.02.18
 * Time: 14:35
 */

namespace AppBundle\Entity;


use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="AppBundle\Repository\SeatsPlanRepository")
 * @ORM\Table(name="seats_plans")
 */
class SeatsPlan
{
	/**
	 * @var int
	 * @ORM\Id()
	 * @ORM\Column(name="seats_plan_id", type="integer")
	 * @ORM\GeneratedValue(strategy="AUTO")
	 */
	private $id;

	/**
	 * @var Schedule|null
	 * @ORM\ManyToOne(targetEntity="Schedule")
	 * @ORM\JoinColumn(name="schedule_id", referencedColumnName="schedule_id", nullable=true)
	 */
	private $schedule;

	/**
	 * @var \DateTime|null
	 * @ORM\Column(name="date_day", type="date", nullable=true)
	 */
	private $dateDay;

	/**
	 * @var Seat[]|ArrayCollection
	 * @ORM\OneToMany(targetEntity="Seat", mappedBy="seatsPlan", cascade={"persist", "remove"}, orphanRemoval=true)
	 */
	private $seats;

	public function __construct()
	{
		$this->seats = new ArrayCollection;
	}

	/**
	 * @return int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * @param int $id
	 */
	public function setId($id)
	{
		$this->id = $id;
	}

	/**
	 * @return Schedule|null
	 */
	public function getSchedule()
	{
		return $this->schedule;
	}

	/**
	 * @param Schedule|null $schedule
	 */
	public function setSchedule(Schedule $schedule)
	{
		$this->schedule = $schedule;
	}

	/**
	 * @return \DateTime|null
	 */
	public function getDateDay()
	{
		return $this->dateDay;
	}

	/**
	 * @param \DateTime|null $dateDay
	 */
	public function setDateDay(\DateTime $dateDay)
	{
		$this->dateDay = $dateDay;
	}

	/**
	 * @return Seat[]|ArrayCollection
	 */
	public function getSeats()
	{
		return $this->seats;
	}

	/**
	 * @param Seat[]|ArrayCollection $seats
	 */
	public function setSeats($seats)
	{
		$this->seats = $seats;
	}

	/**
	 * @return ArrayCollection|Seat[]
	 */
	public function getAvailableSeats()
	{
		return $this->getSeats()->filter(function (Seat $seat) {
			return $seat->isAvailable();
		});
	}

	/**
	 * @return int
	 */
	public function getCountOfAvailableSeats()
	{
		return $this->getSeats()->filter(function (Seat $seat) {
			return $seat->isAvailable();
		})->count();
	}

	/**
	 * @param int $x
	 * @param int $y
	 * @return Seat|null
	 */
	public function getSeatForPosition($x, $y)
	{
		$seats = $this->getSeats()->filter(function (Seat $seat) use ($x, $y) {
			return $seat->getPositionX() == $x and $seat->getPositionY() == $y;
		});

		return $seats->isEmpty() ? null : $seats->first();
	}

	/**
	 * @param int $seatNumber
	 * @return Seat|null
	 */
	public function getSeatByNumber($seatNumber)
	{
		$seats = $this->getSeats()->filter(function (Seat $seat) use ($seatNumber) {
			return $seat->getNumber() == $seatNumber;
		});

		return $seats->isEmpty() ? null : $seats->first();
	}

	/**
	 * @param int $x
	 * @param int $y
	 * @return Seat|null
	 */
	public function createSeatForPosition($x, $y, int $floor = 0)
	{
		$seat = new Seat;
		$seat->setPositionX($x);
		$seat->setPositionY($y);
		$seat->setFloor($floor);

		$this->getSeats()->add($seat);

		return $seat;
	}

	/**
	 * @return int
	 */
	public function getCountOfRows()
	{
		$count = 0;

		$this->getSeats()->map(function (Seat $seat) use (&$count) {
			if ($seat->getPositionY() > $count) $count = $seat->getPositionY();
		});

		return $count;
	}

	/**
	 * @return array
	 */
	public function getRowsOfSeats()
	{
		$rows = [];

		$this->getSeats()->map(function (Seat $seat) use (&$rows) {
			if ($seat->getFloor() !== null) {
				if (!isset($rows[$seat->getFloor()])) {
					$rows[$seat->getFloor()] = [];
				}

				if (!isset($rows[$seat->getFloor()][$seat->getPositionY()])) {
					$rows[$seat->getFloor()][$seat->getPositionY()] = [];
				}

				$rows[$seat->getFloor()][$seat->getPositionY()][$seat->getPositionX()] = $seat;

				return;
			}

			if (!isset($rows[0])) {
				$rows[0] = [];
			}

			if (!isset($rows[0][$seat->getPositionY()])) {
				$rows[0][$seat->getPositionY()] = [];
			}

			$rows[0][$seat->getPositionY()][$seat->getPositionX()] = $seat;
		});

		return $rows;
	}

	public function __clone()
	{
		$this->id = null;
		$seats = new ArrayCollection;
		$this->seats->map(function (Seat $seat) use ($seats) {
			$seats->add(clone $seat);
		});
		$this->seats = $seats;
	}

}

src/AppBundle/Controller/Backend/HomepageController.php
<?php
/**
 * Created by PhpStorm.
 * User: pix
 * Date: 28.06.17
 * Time: 22:57
 */

namespace AppBundle\Controller\Backend;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;

/**
 * @Route(service="")
 */
class HomepageController
{
	/**
	 * @Route(path="/backend", name="backend_homepage", methods={"GET"})
	 * @Template()
	 * @return array
	 */
	public function homepageAction()
	{
		return [

		];
	}
}

src/AppBundle/Controller/Backend/HomepageNoticeController.php
<?php


namespace AppBundle\Controller\Backend;

use AppBundle\Service\HomepageNoticeService;
use AppBundle\Service\LanguageService;
use AppBundle\Widget\Backend\MenuWidget;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Routing\Router;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;

/**
 * @Route(service="controller.backend.homepageNotice")
 */
class HomepageNoticeController
{
	const PARAM_HOMEPAGE_NOTICE = "homepageNotice";
	const PARAM_SHOW = "show";

	/**
	 * @var MenuWidget
	 */
	private $menuWidget;
	/**
	 * @var HomepageNoticeService
	 */
	private $homepageNoticeService;
	/**
	 * @var Router
	 */
	private $router;
	/**
	 * @var LanguageService
	 */
	private $languageService;

	public function __construct(MenuWidget $menuWidget,
								HomepageNoticeService $homepageNoticeService,
								Router $router,
								LanguageService $languageService)
	{
		$this->menuWidget = $menuWidget;
		$this->homepageNoticeService = $homepageNoticeService;
		$this->router = $router;
		$this->languageService = $languageService;
	}

	/**
	 * @Route(path="/backend/homepageNotice", name="backend_homepage_notice", methods={"GET"})
	 * @Template()
	 */
	public function homepageNoticeAction()
	{
		$this->menuWidget->setActive(MenuWidget::ACTIVE_HOMEPAGE_NOTICE);

		return [
			"homepageNotice" => $this->homepageNoticeService->load()
		];
	}

	/**
	 * @Route(path="/backend/homepageNotice", name="backend_homepage_notice_save", methods={"POST"})
	 */
	public function homepageNoticeSaveAction(Request $request)
	{
		$homepageNotice = $this->homepageNoticeService->load();
		$homepageNotice->setShow($request->request->get(self::PARAM_SHOW) === "1");

		foreach ($this->languageService->getAllLanguages() as $lang) {
			$homepageNotice->setContent($lang, $request->request->get(self::PARAM_HOMEPAGE_NOTICE)[$lang->getId()]);
		}

		$this->homepageNoticeService->save($homepageNotice);

		return RedirectResponse::create($this->router->generate("backend_homepage_notice"));
	}
}

src/AppBundle/Resources/views/Backend/Widget/Activity.html.twig
<tr>
    <td><small>{{ activity.datetimeCreated|timeAgo }}</small></td>
    <td>{{ activity.datetimeCreated|date("j. n. Y H:i") }}</td>
    <td>
        {% if activity.user %}
            {% if activity.user.name %}
                {{ activity.user.name }}
            {% elseif activity.user.username %}
                {{ activity.user.username }}
            {% endif %}
        {% endif %}
    </td>
    <td>
        {% if activity.type == "Note" %}Poznámka
        {% elseif activity.type == "InternalTicketGenerated" %}Vygenerována interní jízdenka
        {% elseif activity.type == "OrderPaid" %}Objednávka zaplacena
        {% elseif activity.type == "OrderCreated" %}Objednávka vytvořena
        {% elseif activity.type == "DatetimeReservationChanged" %}Změna délky rezervace
        {% elseif activity.type == "PaymentCreated" %}Vytvořena platba
        {% elseif activity.type == "PaymentSendEmail" %}Odeslán e-mail s platbou
        {% elseif activity.type == "NeedManualTicket" %}Nutné vytvořit jízdenku
        {% elseif activity.type == "ExpiredBook" %}Expirace rezervace
        {% elseif activity.type == "TicketCancel" %}Storno jízdenky
        {% elseif activity.type == "OrderCancel" %}Storno objednávky
        {% elseif activity.type == "TicketBilled" %}Jízdenka vyúčtována
        {% elseif activity.type == "TicketBilledCancel" %}Zrušení vyúčtování jízdenky
        {% endif %}
    </td>
    <td>{{ activity.contentText }}</td>
</tr>

src/AppBundle/Resources/views/Backend/Widget/ExternalTariffConditions.html.twig
<div>
	<form action="{{ path("backend_ajax_external_tariff_conditions_save", { tariff: tariff.id }) }}" method="post">
		<ul class="nav nav-tabs" role="tablist">
			<li role="presentation" class="active"><a href="#tariffConditionsCS" aria-controls="tariffConditionsCS" role="tab" data-toggle="tab">Česky</a></li>
			<li role="presentation"><a href="#tariffConditionsEN" aria-controls="tariffConditionsEN" role="tab" data-toggle="tab">Anglicky</a></li>
			<li role="presentation"><a href="#tariffConditionsRU" aria-controls="tariffConditionsRU" role="tab" data-toggle="tab">Rusky</a></li>
		</ul>
		<div class="tab-content">
			<div role="tabpanel" class="tab-pane active" id="tariffConditionsCS">
				<div class="row">
					<div class="col-md-12">
						<div class="form-group">
							<label for="tariffConditions_cs">Česky:</label>
							<textarea name="tariffConditions[cs]" class="form-control" rows="5" id="tariffConditions_cs">{{ tariff.conditions|languageCS }}</textarea>
						</div>
					</div>
				</div>
			</div>
			<div role="tabpanel" class="tab-pane" id="tariffConditionsEN">
				<div class="row">
					<div class="col-md-12">
						<div class="form-group">
							<label for="tariffConditions_en">Anglicky:</label>
							<textarea name="tariffConditions[en]" class="form-control" rows="5" id="tariffConditions_en">{{ tariff.conditions|languageEN }}</textarea>
						</div>
					</div>
				</div>
			</div>
			<div role="tabpanel" class="tab-pane" id="tariffConditionsRU">
				<div class="row">
					<div class="col-md-12">
						<div class="form-group">
							<label for="tariffConditions_ru">Rusky:</label>
							<textarea name="tariffConditions[ru]" class="form-control" rows="5" id="tariffConditions_ru">{{ tariff.conditions|languageRU }}</textarea>
						</div>
					</div>
				</div>
			</div>
		</div>
	</form>
</div>

src/AppBundle/Resources/views/Backend/Widget/ScheduleSeatsOverview.html.twig
{% for day in days %}
	<p>
		<strong>{{ day.dateDay|date("j. n. Y") }}</strong>, {{ day.dateDay|date("N")|dayInWeek }}<br>
		{% if day.seatsPlan %}
			{{ day.seatsPlan.countOfAvailableSeats }} {% if day.seatsPlan.countOfAvailableSeats == 1 %}sedadlo{% elseif day.seatsPlan.countOfAvailableSeats < 5 %}sedadla{% else %}sedadel{% endif %}<br>
		{% endif %}
		{% for internalTicket in day.internalTickets %}
			<a target="_blank" href="{{ path("backend_order", { order: internalTicket.order.id }) }}">{{ internalTicket.orderPerson.name }}</a> ({{ internalTicket.number }})<br>
		{% endfor %}
	</p>
{% endfor %}

src/AppBundle/Resources/views/Backend/Widget/ScheduleSeatsSettings.html.twig
<tr>
	<td>{{ schedule.line.code }}</td>
	<td>{{ schedule.firstScheduleLineStation.lineStation.city.name|language }} {{ schedule.firstScheduleLineStation.time.departureTime }}</td>
	<td><i class="fa fa-angle-double-right"></i> {{ schedule.lastScheduleLineStation.lineStation.city.name|language }} {{ schedule.lastScheduleLineStation.time.departureTime }}</td>
	<td>{{ seatsPlan.countOfAvailableSeats }}</td>
    {% if isCarrier() %}
        <td>{{ internalTickets|length + books|length }}</td>
    {% else %}
        <td>{{ internalTickets|length }}</td>
        <td>{{ books|length }}</td>
    {% endif %}
	<td><button type="button" data-url="{{ path("backend_ajax_schedule_seats_plan", { line: schedule.line.id, schedule: schedule.id, dateDay: dateDay|date("Y-m-d"), onlyForCarrier: true }) }}" data-action="seatsPlan" class="btn btn-default btn-xs btn-block" style="max-width: 200px;"><i class="fa fa-users"></i> Nastavit místa</button></td>
</tr>

src/AppBundle/Resources/views/Backend/Widget/SeatsPlan.html.twig
<div>
	<form action="{{ actionUrl }}">
		<script type="text/javascript">
			var ticketNumbers = [{% for ticket in internalTickets %}{{ ticket.number }}{% if not loop.last %},{% endif %}{% endfor %}];
            {% if isCarrier() %}
                var bookedNumbers = [];
                {% for book in books %}
                    ticketNumbers.push({{ book.seatNumber }});
                {% endfor %}
            {% else %}
                var bookedNumbers = [{% for book in books %}{{ book.seatNumber }}{% if not loop.last %},{% endif %}{% endfor %}];
            {% endif %}
			var onlyForCarrier = {{ onlyForCarrier ? "true" : "false" }};
		</script>
		<input type="hidden" name="dateDay" value="{% if dateDay %}{{ dateDay|date("Y-m-d") }}{% endif %}">
		<div class="row">
			<div class="{% if onlyForCarrier %}col-md-12{% else %}col-md-5{% endif %}">
				{% if not onlyForCarrier %}
				<button type="button" class="btn btn-default pull-right btn-block" data-action="addRow">+ Přidat řadu</button>
				<br><br>
				{% endif %}
				<table class="seats-plan">
					<tbody>
					{% for row in seatsPlan.rowsOfSeats[0] %}
					<tr>
						{% for x in 0..4 %}
							{% if row[x] is not defined %}
								<td></td>
							{% elseif row[x].available %}
								<td class="seat-available"></td>
							{% else %}
								<td class="seat"></td>
							{% endif %}
						{% endfor %}
						{% if not onlyForCarrier %}
						<td class="control"><button type="button" class="btn btn-default btn-xs" data-action="removeRow">-</button></td>
						{% endif %}
					</tr>
					{% endfor %}
					</tbody>
				</table>
			</div>
			{% if not onlyForCarrier %}
			<div class="col-md-7">
				{% if (seatsPlan.dateDay is null and seatsPlan.id) or seatsPlan.dateDay %}
				<button type="button" class="btn btn-primary pull-right" data-action="setForDate" {% if dateDay %}style="display:none"{% endif %}>Nastavit na konkrétní datum</button>
				<button type="button" class="btn btn-primary pull-right" data-action="setForSchedule" {% if dateDay is null %}style="display:none"{% endif %}>Nastavit pro celý spoj</button>
				<br><br>
				<div class="calendar pull-right" {% if dateDay is null %}style="display:none"{% endif %}></div>
				{% endif %}
			</div>
			{% endif %}
		</div>
	</form>
</div>