src/AppBundle/Entity/City.php
<?php
/**
 * Created by PhpStorm.
 * User: pix
 * Date: 13.04.17
 * Time: 12:10
 */

namespace AppBundle\Entity;


use AppBundle\VO\ExternalRouter;
use AppBundle\VO\LanguageString;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Config\Definition\Exception\Exception;

/**
 * @ORM\Entity(repositoryClass="AppBundle\Repository\CityRepository")
 * @ORM\Table(name="cities")
 */
class City
{
	/**
	 * @var int
	 * @ORM\Id()
	 * @ORM\Column(name="city_id", type="integer")
	 * @ORM\GeneratedValue(strategy="AUTO")
	 */
	private $id;

	/**
	 * @var LanguageString
	 * @ORM\Column(name="name", type="object", nullable=false)
	 */
	private $name;

	/**
	 * @var LanguageString
	 * @ORM\Column(name="next_variations", type="string", nullable=false)
	 */
	private $nextVariations = "";

	/**
	 * @var Country
	 * @ORM\ManyToOne(targetEntity="Country", inversedBy="cities")
	 * @ORM\JoinColumn(name="country_id", referencedColumnName="country_id", nullable=false)
	 */
	private $country;

	/**
	 * @var Station[]|ArrayCollection
	 * @ORM\OneToMany(targetEntity="Station", mappedBy="city")
	 */
	private $stations;

	/**
	 * @var ExternalCity[]|ArrayCollection
	 * @ORM\OneToMany(targetEntity="ExternalCity", mappedBy="city")
	 */
	private $externalCities;

	/**
	 * @var boolean
	 * @ORM\Column(name="deleted", type="boolean", nullable=false)
	 */
	private $deleted = false;

	public function __construct()
	{
		$this->name = new LanguageString;
		$this->stations = new ArrayCollection;
	}

	/**
	 * @return int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * @param int $id
	 */
	public function setId($id)
	{
		$this->id = $id;
	}

	/**
	 * @return LanguageString
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * @param Language $language
	 * @param string $name
	 */
	public function setName(Language $language, $name)
	{
		$this->name = clone $this->getName()->setString($language, $name);
	}

	/**
	 * @return Country
	 */
	public function getCountry()
	{
		return $this->country;
	}

	/**
	 * @param Country $country
	 */
	public function setCountry($country)
	{
		$this->country = $country;
	}

	/**
	 * @return \string[]
	 */
	public function getAllLanguagesNames()
	{
		return $this->getName()->getAllLanguagesStrings();
	}

	/**
	 * @return Station[]|ArrayCollection
	 */
	public function getStations()
	{
		return $this->stations;
	}

	/**
	 * @param Station[]|ArrayCollection $stations
	 */
	public function setStations($stations)
	{
		$this->stations = $stations;
	}

	/**
	 * @return ExternalCity[]|ArrayCollection
	 */
	public function getExternalCities()
	{
		return $this->externalCities;
	}

	/**
	 * @param ExternalCity[]|ArrayCollection $externalCities
	 */
	public function setExternalCities($externalCities)
	{
		$this->externalCities = $externalCities;
	}

	/**
	 * @param string $type
	 * @return ExternalCity|null
	 */
	public function getExternalCity($type)
	{
		return !$this->getExternalCitiesByType($type)->isEmpty() ? $this->getExternalCitiesByType($type)->first() : null;
	}

	/**
	 * @param string $type
	 * @return ExternalCity[]|ArrayCollection
	 */
	public function getExternalCitiesByType($type)
	{
		return $this->getExternalCities()->filter(function ($externalCity) use ($type) {
			if ($type == ExternalRouter::STUDENT_AGENCY and $externalCity instanceof ExternalCityStudentAgency) {
				return true;
			} elseif ($type == ExternalRouter::ECOLINES and $externalCity instanceof ExternalCityEcolines) {
				return true;
			} elseif ($type == ExternalRouter::INFOBUS and $externalCity instanceof ExternalCityInfobus) {
				return true;
			} elseif ($type == ExternalRouter::EAST_EXPRESS and $externalCity instanceof ExternalCityEastExpress) {
				return true;
			} elseif ($type == ExternalRouter::FLIXBUS and $externalCity instanceof ExternalCityFlixbus) {
				return true;
			} elseif ($type == ExternalRouter::NIKOLO and $externalCity instanceof ExternalCityNikoloBusSystem) {
				return true;
			} elseif ($type == ExternalRouter::EUROLINES and $externalCity instanceof ExternalCityEurolines) {
				return true;
			} elseif ($type == ExternalRouter::REGABUS and $externalCity instanceof ExternalCityRegabus) {
				return true;
			} elseif ($type == ExternalRouter::BLABLA and $externalCity instanceof ExternalCityBlabla) {
				return true;
			} elseif ($type == ExternalRouter::TRANS_TEMPO and $externalCity instanceof ExternalCityTransTempo) {
				return true;
			} elseif ($type == ExternalRouter::LIKEBUS and $externalCity instanceof ExternalCityLikeBus) {
				return true;
			}

			return false;
		});
	}

	/**
	 * @return LanguageString
	 */
	public function getNextVariations()
	{
		return $this->nextVariations;
	}

	/**
	 * @param LanguageString $nextVariations
	 */
	public function setNextVariations($nextVariations)
	{
		$this->nextVariations = $nextVariations;
	}

	/**
	 * @return bool
	 */
	public function isDeleted(): bool
	{
		return $this->deleted;
	}

	/**
	 * @param bool $deleted
	 */
	public function setDeleted(bool $deleted)
	{
		$this->deleted = $deleted;
	}

}

src/AppBundle/Entity/Schedule.php
<?php
/**
 * Created by PhpStorm.
 * User: pix
 * Date: 13.04.17
 * Time: 15:01
 */

namespace AppBundle\Entity;


use AppBundle\VO\DayRange;
use AppBundle\VO\Days;
use AppBundle\VO\LanguageString;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="AppBundle\Repository\ScheduleRepository")
 * @ORM\Table(name="schedules")
 */
class Schedule
{
	/**
	 * @var int
	 * @ORM\Id()
	 * @ORM\Column(name="schedule_id", type="integer")
	 * @ORM\GeneratedValue(strategy="AUTO")
	 */
	private $id;

	/**
	 * @var Line
	 * @ORM\ManyToOne(targetEntity="Line", inversedBy="schedules")
	 * @ORM\JoinColumn(name="line_id", referencedColumnName="line_id", nullable=false)
	 */
	private $line;

	/**
	 * @var int[]|ArrayCollection
	 * @ORM\Column(name="week_days", type="array", nullable=false)
	 */
	private $weekDays;

	/**
	 * @var Days
	 * @ORM\Column(name="include_days", type="object", nullable=false)
	 */
	private $includeDays;

	/**
	 * @var Days
	 * @ORM\Column(name="exclude_days", type="object", nullable=false)
	 */
	private $excludeDays;

	/**
	 * @var ScheduleLineStation[]|ArrayCollection
	 * @ORM\OneToMany(targetEntity="ScheduleLineStation", mappedBy="schedule", cascade={"all"})
	 */
	private $scheduleLineStations;

	/**
	 * @var string
	 * @ORM\Column(name="direction", type="string", length=32, nullable=false)
	 */
	private $direction;

	/**
	 * @var int
	 * @ORM\Column(name="old_price_table_number", type="integer", nullable=true)
	 */
	private $oldPriceTableNumber;

	/**
	 * @var Tariff
	 * @ORM\ManyToOne(targetEntity="Tariff")
	 * @ORM\JoinColumn(name="tariff_id", referencedColumnName="tariff_id", nullable=true)
	 */
	private $tariff;

	/**
	 * @var Tariff[]|ArrayCollection
	 * @ORM\ManyToMany(targetEntity="Tariff", cascade={"persist"})
	 * @ORM\JoinTable(
	 *     name="schedules_tariffs",
	 *     joinColumns={@ORM\JoinColumn(name="schedule_id", referencedColumnName="schedule_id")},
	 *     inverseJoinColumns={@ORM\JoinColumn(name="tariff_id", referencedColumnName="tariff_id")}
	 * )
	 */
	private $tariffs;

	/**
	 * @var int
	 * @ORM\Column(name="own_seats", type="integer", nullable=true)
	 */
	private $ownSeats;

	/**
	 * @var boolean
	 * @ORM\Column(name="deleted", type="boolean", nullable=false)
	 */
	private $deleted = false;

	/**
	 * @var int
	 * @ORM\Column(name="weight", type="smallint", nullable=false)
	 */
	private $weight = 0;

	/**
	 * @var LanguageString
	 * @ORM\Column(name="private_note", type="object", nullable=false)
	 */
	private $privateNote;

	/**
	 * @var LanguageString
	 * @ORM\Column(name="public_note", type="object", nullable=false)
	 */
	private $publicNote;

	/**
	 * @var bool
	 * @ORM\Column(name="seats_without_numbers", type="boolean", nullable=false)
	 */
	private $seatsWithoutNumbers = false;

	/**
	 * @var bool
	 * @ORM\Column(name="pay_online_disabled", type="boolean", nullable=false)
	 */
	private $payOnlineDisabled = false;

	public function __construct()
	{
		$this->weekDays = new ArrayCollection;
		$this->scheduleLineStations = new ArrayCollection;
		$this->tariffs = new ArrayCollection;
		$this->includeDays = new Days;
		$this->includeDays->setAll(true);
		$this->excludeDays = new Days;
	}

	/**
	 * @return int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * @param int $id
	 */
	public function setId($id)
	{
		$this->id = $id;
	}

	/**
	 * @return Line
	 */
	public function getLine()
	{
		return $this->line;
	}

	/**
	 * @param Line $line
	 */
	public function setLine($line)
	{
		$this->line = $line;
	}

	/**
	 * @return ArrayCollection|\int[]
	 */
	public function getWeekDays()
	{
		if ($this->weekDays instanceof ArrayCollection) {
			return $this->weekDays;
		} else {
			return new ArrayCollection($this->weekDays);
		}
	}

	/**
	 * @param int $day
	 */
	public function addWeekDay($day)
	{
		if (!$this->getWeekDays()->contains($day)) {
			$this->getWeekDays()->add($day);
		}
	}

	/**
	 * @param ArrayCollection|\int[] $weekDays
	 */
	public function setWeekDays($weekDays)
	{
		$this->weekDays = $weekDays;
	}

	/**
	 * @return Days
	 */
	public function getExcludeDays()
	{
		return $this->excludeDays;
	}

	/**
	 * @param Days $excludeDays
	 */
	public function setExcludeDays($excludeDays)
	{
		$this->excludeDays = $excludeDays;
	}

	/**
	 * @return Days
	 */
	public function getIncludeDays()
	{
		return $this->includeDays;
	}

	/**
	 * @param Days $includeDays
	 */
	public function setIncludeDays($includeDays)
	{
		$this->includeDays = $includeDays;
	}

	/**
	 * @return ScheduleLineStation[]|ArrayCollection
	 */
	public function getScheduleLineStations()
	{
		return $this->scheduleLineStations;
	}

	/**
	 * @return ScheduleLineStation[]|ArrayCollection
	 */
	public function getActiveScheduleLineStations()
	{
		return $this->scheduleLineStations->filter(function (ScheduleLineStation $sls) {
			return !$sls->isDeleted();
		});
	}

	/**
	 * @param ScheduleLineStation[]|ArrayCollection $scheduleLineStations
	 */
	public function setScheduleLineStations($scheduleLineStations)
	{
		$this->scheduleLineStations = $scheduleLineStations;
	}

	/**
	 * @param ScheduleLineStation $scheduleLineStation
	 */
	public function addScheduleLineStation(ScheduleLineStation $scheduleLineStation)
	{
		$this->scheduleLineStations->add($scheduleLineStation);
		$scheduleLineStation->setSchedule($this);
	}

	/**
	 * @param City $city
	 * @return ScheduleLineStation|null
	 */
	public function getScheduleLineStationForCity(City $city)
	{
		/** @var ArrayCollection|ScheduleLineStation[] $return */
		$return = $this->getActiveScheduleLineStations()->filter(function (ScheduleLineStation $scheduleLineStation) use ($city) {
			return $scheduleLineStation->getLineStation()->getCity() == $city;
		});

		return $return->isEmpty() ? null : $return->first();
	}

	/**
	 * @param City $city
	 * @return ScheduleLineStation[]|ArrayCollection|null
	 */
	public function getScheduleLineStationsForCity(City $city)
	{
		/** @var ArrayCollection|ScheduleLineStation[] $return */
		$return = $this->getActiveScheduleLineStations()->filter(function (ScheduleLineStation $scheduleLineStation) use ($city) {
			return $scheduleLineStation->getLineStation()->getCity() === $city;
		});

		return $return;
	}

	/**
	 * @param LineStation $lineStation
	 * @return ScheduleLineStation|null
	 */
	public function getScheduleLineStationsForLineStation(LineStation $lineStation)
	{
		/** @var ArrayCollection|ScheduleLineStation[] $return */
		$return = $this->getActiveScheduleLineStations()->filter(function (ScheduleLineStation $scheduleLineStation) use ($lineStation) {
			return $scheduleLineStation->getLineStation() === $lineStation;
		});

		return $return->isEmpty() ? null : $return->first();
	}

	/**
	 * @return string
	 */
	public function getDirection()
	{
		return $this->direction;
	}

	/**
	 * @param string $direction
	 */
	public function setDirection($direction)
	{
		$this->direction = $direction;
	}

	/**
	 * @return int
	 */
	public function getOldPriceTableNumber()
	{
		return $this->oldPriceTableNumber;
	}

	/**
	 * @param int $oldPriceTableNumber
	 */
	public function setOldPriceTableNumber($oldPriceTableNumber)
	{
		$this->oldPriceTableNumber = $oldPriceTableNumber;
	}

	/**
	 * @return Tariff
	 * @deprecated
	 */
	public function getTariff()
	{
		return $this->tariff;
	}

	/**
	 * @param Tariff $tariff
	 * @deprecated
	 */
	public function setTariff($tariff)
	{
		$this->tariff = $tariff;
	}

	/**
	 * @return Tariff[]|ArrayCollection
	 */
	public function getTariffs()
	{
		return $this->tariffs;
	}

	/**
	 * @return Tariff[]|ArrayCollection
	 */
	public function getActiveTariffs()
	{
		return $this->tariffs->filter(function (Tariff $tariff) {
			return !$tariff->isDeleted();
		});
	}

	/**
	 * @param Tariff[]|ArrayCollection $tariffs
	 */
	public function setTariffs($tariffs)
	{
		$this->tariffs = $tariffs;
	}

	/**
	 * @return int
	 */
	public function getOwnSeats()
	{
		return $this->ownSeats;
	}

	/**
	 * @param int $ownSeats
	 */
	public function setOwnSeats($ownSeats)
	{
		$this->ownSeats = $ownSeats;
	}

	/**
	 * @return boolean
	 */
	public function isDeleted()
	{
		return $this->deleted;
	}

	/**
	 * @param boolean $deleted
	 */
	public function setDeleted($deleted)
	{
		$this->deleted = $deleted;
	}

	function __clone()
	{
		$this->setId(null);
	}

	/**
	 * @return int
	 */
	public function getWeight()
	{
		return $this->weight;
	}

	/**
	 * @param int $weight
	 */
	public function setWeight($weight)
	{
		$this->weight = $weight;
	}

	/**
	 * @param string $direction
	 * @return ScheduleLineStation|null
	 */
	public function getFirstScheduleLineStation()
	{
		/** @var ScheduleLineStation $return */
		$return = null;

		$this->getLine()->getLineStations($this->getDirection())->map(function (LineStation $lineStation) use (&$return) {
			$scheduleLineStation = $this->getScheduleLineStationsForLineStation($lineStation);
			if ($scheduleLineStation and $scheduleLineStation->getTime()->getDepartureTime()) {
				if ($return === null) $return = $scheduleLineStation;
			}
		});

		return $return;
	}

	/**
	 * @param string $direction
	 * @return ScheduleLineStation|null
	 */
	public function getLastScheduleLineStation()
	{
		/** @var ScheduleLineStation $return */
		$return = null;

		$this->getLine()->getLineStations($this->getDirection())->map(function (LineStation $lineStation) use (&$return) {
			$scheduleLineStation = $this->getScheduleLineStationsForLineStation($lineStation);
			if ($scheduleLineStation and $scheduleLineStation->getTime()->getDepartureTime()) {
				$return = $scheduleLineStation;
			}
		});

		return $return;
	}

	/**
	 * @return LanguageString
	 */
	public function getPrivateNote()
	{
		return $this->privateNote;
	}

	/**
	 * @param Language $language
	 * @param string $privateNote
	 */
	public function setPrivateNote(Language $language, $privateNote)
	{

src/AppBundle/Controller/Backend/HomepageController.php
<?php
/**
 * Created by PhpStorm.
 * User: pix
 * Date: 28.06.17
 * Time: 22:57
 */

namespace AppBundle\Controller\Backend;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;

/**
 * @Route(service="")
 */
class HomepageController
{
	/**
	 * @Route(path="/backend", name="backend_homepage", methods={"GET"})
	 * @Template()
	 * @return array
	 */
	public function homepageAction()
	{
		return [

		];
	}
}

src/AppBundle/Controller/Backend/HomepageNoticeController.php
<?php


namespace AppBundle\Controller\Backend;

use AppBundle\Service\HomepageNoticeService;
use AppBundle\Service\LanguageService;
use AppBundle\Widget\Backend\MenuWidget;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Routing\Router;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;

/**
 * @Route(service="controller.backend.homepageNotice")
 */
class HomepageNoticeController
{
	const PARAM_HOMEPAGE_NOTICE = "homepageNotice";
	const PARAM_SHOW = "show";

	/**
	 * @var MenuWidget
	 */
	private $menuWidget;
	/**
	 * @var HomepageNoticeService
	 */
	private $homepageNoticeService;
	/**
	 * @var Router
	 */
	private $router;
	/**
	 * @var LanguageService
	 */
	private $languageService;

	public function __construct(MenuWidget $menuWidget,
								HomepageNoticeService $homepageNoticeService,
								Router $router,
								LanguageService $languageService)
	{
		$this->menuWidget = $menuWidget;
		$this->homepageNoticeService = $homepageNoticeService;
		$this->router = $router;
		$this->languageService = $languageService;
	}

	/**
	 * @Route(path="/backend/homepageNotice", name="backend_homepage_notice", methods={"GET"})
	 * @Template()
	 */
	public function homepageNoticeAction()
	{
		$this->menuWidget->setActive(MenuWidget::ACTIVE_HOMEPAGE_NOTICE);

		return [
			"homepageNotice" => $this->homepageNoticeService->load()
		];
	}

	/**
	 * @Route(path="/backend/homepageNotice", name="backend_homepage_notice_save", methods={"POST"})
	 */
	public function homepageNoticeSaveAction(Request $request)
	{
		$homepageNotice = $this->homepageNoticeService->load();
		$homepageNotice->setShow($request->request->get(self::PARAM_SHOW) === "1");

		foreach ($this->languageService->getAllLanguages() as $lang) {
			$homepageNotice->setContent($lang, $request->request->get(self::PARAM_HOMEPAGE_NOTICE)[$lang->getId()]);
		}

		$this->homepageNoticeService->save($homepageNotice);

		return RedirectResponse::create($this->router->generate("backend_homepage_notice"));
	}
}

src/AppBundle/Resources/views/Backend/Schedule/schedules.html.twig
{% extends 'AppBundle:Backend/Layout:Skeleton.html.twig' %}

{% import "@App/Backend/Macro/line.html.twig" as lineMacro %}

{% block content %}

	<div class="container">
		<form action="" method="get">
			<div class="row">
				<div class="col-md-2">
					<div class="form-group">
						<label for="filterFromCity">Odkud</label><br>
						<select id="filterFromCity" name="filterFromCity" class="selectpicker" data-live-search="true" data-live-search-style="startsWith" data-width="100%">
							<option value="">Odkud</option>
							{% for country in countries %}
								<optgroup label="{{ country.name|language }}">
									{% for city in country.cities %}
										<option data-tokens="{{ city.allLanguagesNames|join(" ") }} {{ city.nextVariations }}" value="{{ city.id }}"{% if routeFilter.fromCity == city or (routeFilter.fromCity is null and fromCity == city)%} selected{% endif %}>{{ city.name|language }}</option>
									{% endfor %}
								</optgroup>
							{% endfor %}
						</select>
					</div>
				</div>
				<div class="col-md-2">
					<div class="form-group">
						<label for="filterToCity">Kam</label><br>
						<select id="filterToCity" name="filterToCity" class="selectpicker" data-live-search="true" data-live-search-style="startsWith" data-width="100%">
							<option value="">Kam</option>
							{% for country in countries %}
								<optgroup label="{{ country.name|language }}">
									{% for city in country.cities %}
										<option data-tokens="{{ city.allLanguagesNames|join(" ") }} {{ city.nextVariations }}" value="{{ city.id }}"{% if routeFilter.toCity == city or (routeFilter.toCity is null and toCity == city)%} selected{% endif %}>{{ city.name|language }}</option>
									{% endfor %}
								</optgroup>
							{% endfor %}
						</select>
					</div>
				</div>
				<div class="col-md-2">
					<label for="filterDay">Datum</label><br>
					<input type="text" class="form-control" value="{% if routeFilter.dateDay %}{{ routeFilter.dateDay|dateFormat }}{% else %}{{ "now"|dateFormat }}{% endif %}" name="filterDay" id="filterDay" style="width: 100%">
				</div>
				<div class="col-md-2">
					<button type="submit" class="btn btn-success btn-block" style="margin-top: 25px"><i class="fa fa-refresh"></i> Obnovit</button>
				</div>
			</div>
		</form>

		<div class="row">
			<div class="col-md-12">
				{% for carrier in carriers %}
					{% set exists = false %}
					{% for schedule in schedules if schedule.line.carrier == carrier %}
						{% set exists = true %}
					{% endfor %}
					{% if exists %}
						<h2>{{ carrier.name }}</h2>
						<table class="table table-bordered table-hover">
							<thead>
							<tr>
								<th>Linka</th>
								<th>Vyjíždí z</th>
								<th>Odkud</th>
								<th>Kam</th>
								<th>Konečná stanice</th>
								<th>Dny v týdnu</th>
								<th>Míst</th>
								<th>Koupených</th>
							</tr>
							</thead>
							<tbody>
							{% for schedule in schedules if schedule.line.carrier == carrier %}
								<tr>
									<td><a href="{{ path("backend_line", { line: schedule.line.id }) }}" class="td-a">{{ schedule.line.code }}</a></td>
									<td><a href="{{ path("backend_line", { line: schedule.line.id }) }}" class="td-a">{{ schedule.firstScheduleLineStation.lineStation.city.name|language }} {{ schedule.firstScheduleLineStation.time.departureTime }}</a></td>
									<td><a href="{{ path("backend_line", { line: schedule.line.id }) }}" class="td-a"><i class="fa fa-angle-double-right"></i> <strong>{{ schedule.scheduleLineStationForCity(routeFilter.fromCity).lineStation.city.name|language }} {{ schedule.scheduleLineStationForCity(routeFilter.fromCity).time.departureTime }}</strong></a></td>
									<td><a href="{{ path("backend_line", { line: schedule.line.id }) }}" class="td-a"><i class="fa fa-angle-double-right"></i> <strong>{{ schedule.scheduleLineStationForCity(routeFilter.toCity).lineStation.city.name|language }} {{ schedule.scheduleLineStationForCity(routeFilter.toCity).time.departureTime }}</strong></a></td>
									<td><a href="{{ path("backend_line", { line: schedule.line.id }) }}" class="td-a"><i class="fa fa-angle-double-right"></i> {{ schedule.lastScheduleLineStation.lineStation.city.name|language }} {{ schedule.lastScheduleLineStation.time.departureTime }}</a></td>
									<td><a href="{{ path("backend_line", { line: schedule.line.id }) }}" class="td-a">{% for weekDay in schedule.weekDays %}<span style="margin-right: 5px; {% if weekDay == routeFilter.dateDay.format("N")-1 %}font-weight: bold{% endif %}">{{ weekDay }}</span>{% endfor %}</a></td>
									<td><a href="{{ path("backend_line", { line: schedule.line.id }) }}" class="td-a"></a></td>
									<td><a href="{{ path("backend_line", { line: schedule.line.id }) }}" class="td-a"></a></td>
								</tr>
							{% endfor %}
							</tbody>
						</table>
					{% endif %}
				{% endfor %}
			</div>
		</div>
	</div>

{% endblock %}