src/AppBundle/Entity/Book.php
<?php
/**
 * Created by PhpStorm.
 * User: pix
 * Date: 11.01.18
 * Time: 10:53
 */

namespace AppBundle\Entity;
use AppBundle\VO\PriceCurrency;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="AppBundle\Repository\BookRepository")
 * @ORM\Table(name="books")
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="type", type="string")
 * @ORM\DiscriminatorMap(
 *     {
 *         "internal" = "BookInternal",
 *         "student_agency" = "BookStudentAgency",
 *         "nikolo" = "BookNikolo",
 *         "infobus" = "BookInfobus",
 *         "ecolines" = "BookEcolines",
 *         "regabus" = "BookRegabus",
 *         "blabla" = "BookBlabla",
 *         "trans_tempo" = "BookTransTempo",
 *         "likebus" = "BookLikeBus"
 *     }
 * )
 */
abstract class Book
{
	/**
	 * @var string
	 * @ORM\Id()
	 * @ORM\Column(name="book_id", type="string", length=64)
	 * @ORM\GeneratedValue(strategy="UUID")
	 */
	protected $id;

	/**
	 * @var \DateTime
	 * @ORM\Column(name="datetime_created", type="datetime", nullable=false)
	 */
	protected $datetimeCreated;

	/**
	 * @var Order
	 * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Order", inversedBy="books")
	 * @ORM\JoinColumn(name="order_id", referencedColumnName="order_id", nullable=true)
	 */
	protected $order;

	/**
	 * @var boolean
	 * @ORM\Column(name="cancelled", type="boolean", nullable=false)
	 */
	private $cancelled = false;

	/**
	 * @var \DateTime
	 * @ORM\Column(name="datetime_cancelled", type="datetime", nullable=true)
	 */
	private $datetimeCancelled;

	/**
	 * @var OrderPersonRouteTariff
	 * @ORM\OneToOne(targetEntity="AppBundle\Entity\OrderPersonRouteTariff", mappedBy="book")
	 */
	private $orderPersonRouteTariff;

	/**
	 * @var float
	 * @ORM\Column(name="price", type="decimal", precision=10, scale=2, nullable=true)
	 */
	private $price;

	/**
	 * @var float
	 * @ORM\Column(name="price_include_surcharge", type="decimal", precision=10, scale=2, nullable=true)
	 */
	private $priceIncludeSurcharge;

	/**
	 * @var Route|null
	 * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Route", inversedBy="books")
	 * @ORM\JoinColumn(name="route_id", referencedColumnName="route_id", nullable=true)
	 */
	private $route;

	public function __construct()
	{
		$this->datetimeCreated = new \DateTime;
	}

	/**
	 * @return string
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * @param string $id
	 */
	public function setId($id)
	{
		$this->id = $id;
	}

	/**
	 * @return \DateTime
	 */
	public function getDatetimeCreated()
	{
		return $this->datetimeCreated;
	}

	/**
	 * @param \DateTime $datetimeCreated
	 */
	public function setDatetimeCreated(\DateTime $datetimeCreated)
	{
		$this->datetimeCreated = $datetimeCreated;
	}

	/**
	 * @return Order
	 */
	public function getOrder()
	{
		return $this->order;
	}

	/**
	 * @param Order $order
	 */
	public function setOrder($order)
	{
		$this->order = $order;
	}

	/**
	 * @return bool
	 */
	public function isStillValid()
	{
		if ($this->isCancelled()) return false;

		if ($this->getOrder()->getDateReservationDay()) {
			$datetimeLimit = new \DateTime($this->getOrder()->getDateReservationDay()->format("Y-m-d 23:59:59"));
			return $datetimeLimit > new \DateTime;
		}

		return true;
	}

	/**
	 * @return bool
	 */
	public function isCancelled()
	{
		return $this->cancelled;
	}

	/**
	 * @param bool $cancelled
	 */
	public function setCancelled($cancelled)
	{
		$this->cancelled = $cancelled;
	}

	/**
	 * @return \DateTime
	 */
	public function getDatetimeCancelled()
	{
		return $this->datetimeCancelled;
	}

	/**
	 * @param \DateTime $datetimeCancelled
	 */
	public function setDatetimeCancelled($datetimeCancelled)
	{
		$this->datetimeCancelled = $datetimeCancelled;
	}

	/**
	 * @return OrderPersonRouteTariff
	 */
	public function getOrderPersonRouteTariff()
	{
		return $this->orderPersonRouteTariff;
	}

	/**
	 * @param OrderPersonRouteTariff $orderPersonRouteTariff
	 */
	public function setOrderPersonRouteTariff($orderPersonRouteTariff)
	{
		$this->orderPersonRouteTariff = $orderPersonRouteTariff;
	}

	/**
	 * @return PriceCurrency
	 */
	public function getPriceCurrency()
	{
		return PriceCurrency::create($this->price, $this->getCurrency());
	}

	/**
	 * @param float $price
	 */
	public function setPrice($price)
	{
		$this->price = $price;
	}

	/**
	 * @return PriceCurrency
	 */
	public function getPriceCurrencyIncludeSurcharge()
	{
		return PriceCurrency::create($this->priceIncludeSurcharge, $this->getCurrency());
	}

	/**
	 * @param float $priceIncludeSurcharge
	 */
	public function setPriceIncludeSurcharge($priceIncludeSurcharge)
	{
		$this->priceIncludeSurcharge = $priceIncludeSurcharge;
	}

	/**
	 * @return string
	 */
	public function getCurrency()
	{
		return $this->getOrder()->getCurrency();
	}

	public function countPrices()
	{
		if ($this->getOrderPersonRouteTariff()->getChangedPrice() !== null) {
			$this->setPrice($this->getOrderPersonRouteTariff()->getChangedPrice());
			$this->setPriceIncludeSurcharge($this->getOrderPersonRouteTariff()->getChangedPrice());
		} else {
			$this->setPrice($this->getOrderPersonRouteTariff()->getRouteTariff()->getPrice());
			$this->setPriceIncludeSurcharge($this->getOrderPersonRouteTariff()->getRouteTariff()->getPriceIncludeSurcharge());
		}
	}

	/**
	 * @return Route|null
	 */
	public function getRoute()
	{
		return $this->route;
	}

	/**
	 * @param Route|null $route
	 */
	public function setRoute($route)
	{
		$this->route = $route;
		$route->getBooks()->add($this);
	}

}

src/AppBundle/Entity/SeatsPlan.php
<?php
/**
 * Created by PhpStorm.
 * User: pix
 * Date: 15.02.18
 * Time: 14:35
 */

namespace AppBundle\Entity;


use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="AppBundle\Repository\SeatsPlanRepository")
 * @ORM\Table(name="seats_plans")
 */
class SeatsPlan
{
	/**
	 * @var int
	 * @ORM\Id()
	 * @ORM\Column(name="seats_plan_id", type="integer")
	 * @ORM\GeneratedValue(strategy="AUTO")
	 */
	private $id;

	/**
	 * @var Schedule|null
	 * @ORM\ManyToOne(targetEntity="Schedule")
	 * @ORM\JoinColumn(name="schedule_id", referencedColumnName="schedule_id", nullable=true)
	 */
	private $schedule;

	/**
	 * @var \DateTime|null
	 * @ORM\Column(name="date_day", type="date", nullable=true)
	 */
	private $dateDay;

	/**
	 * @var Seat[]|ArrayCollection
	 * @ORM\OneToMany(targetEntity="Seat", mappedBy="seatsPlan", cascade={"persist", "remove"}, orphanRemoval=true)
	 */
	private $seats;

	public function __construct()
	{
		$this->seats = new ArrayCollection;
	}

	/**
	 * @return int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * @param int $id
	 */
	public function setId($id)
	{
		$this->id = $id;
	}

	/**
	 * @return Schedule|null
	 */
	public function getSchedule()
	{
		return $this->schedule;
	}

	/**
	 * @param Schedule|null $schedule
	 */
	public function setSchedule(Schedule $schedule)
	{
		$this->schedule = $schedule;
	}

	/**
	 * @return \DateTime|null
	 */
	public function getDateDay()
	{
		return $this->dateDay;
	}

	/**
	 * @param \DateTime|null $dateDay
	 */
	public function setDateDay(\DateTime $dateDay)
	{
		$this->dateDay = $dateDay;
	}

	/**
	 * @return Seat[]|ArrayCollection
	 */
	public function getSeats()
	{
		return $this->seats;
	}

	/**
	 * @param Seat[]|ArrayCollection $seats
	 */
	public function setSeats($seats)
	{
		$this->seats = $seats;
	}

	/**
	 * @return ArrayCollection|Seat[]
	 */
	public function getAvailableSeats()
	{
		return $this->getSeats()->filter(function (Seat $seat) {
			return $seat->isAvailable();
		});
	}

	/**
	 * @return int
	 */
	public function getCountOfAvailableSeats()
	{
		return $this->getSeats()->filter(function (Seat $seat) {
			return $seat->isAvailable();
		})->count();
	}

	/**
	 * @param int $x
	 * @param int $y
	 * @return Seat|null
	 */
	public function getSeatForPosition($x, $y)
	{
		$seats = $this->getSeats()->filter(function (Seat $seat) use ($x, $y) {
			return $seat->getPositionX() == $x and $seat->getPositionY() == $y;
		});

		return $seats->isEmpty() ? null : $seats->first();
	}

	/**
	 * @param int $seatNumber
	 * @return Seat|null
	 */
	public function getSeatByNumber($seatNumber)
	{
		$seats = $this->getSeats()->filter(function (Seat $seat) use ($seatNumber) {
			return $seat->getNumber() == $seatNumber;
		});

		return $seats->isEmpty() ? null : $seats->first();
	}

	/**
	 * @param int $x
	 * @param int $y
	 * @return Seat|null
	 */
	public function createSeatForPosition($x, $y, int $floor = 0)
	{
		$seat = new Seat;
		$seat->setPositionX($x);
		$seat->setPositionY($y);
		$seat->setFloor($floor);

		$this->getSeats()->add($seat);

		return $seat;
	}

	/**
	 * @return int
	 */
	public function getCountOfRows()
	{
		$count = 0;

		$this->getSeats()->map(function (Seat $seat) use (&$count) {
			if ($seat->getPositionY() > $count) $count = $seat->getPositionY();
		});

		return $count;
	}

	/**
	 * @return array
	 */
	public function getRowsOfSeats()
	{
		$rows = [];

		$this->getSeats()->map(function (Seat $seat) use (&$rows) {
			if ($seat->getFloor() !== null) {
				if (!isset($rows[$seat->getFloor()])) {
					$rows[$seat->getFloor()] = [];
				}

				if (!isset($rows[$seat->getFloor()][$seat->getPositionY()])) {
					$rows[$seat->getFloor()][$seat->getPositionY()] = [];
				}

				$rows[$seat->getFloor()][$seat->getPositionY()][$seat->getPositionX()] = $seat;

				return;
			}

			if (!isset($rows[0])) {
				$rows[0] = [];
			}

			if (!isset($rows[0][$seat->getPositionY()])) {
				$rows[0][$seat->getPositionY()] = [];
			}

			$rows[0][$seat->getPositionY()][$seat->getPositionX()] = $seat;
		});

		return $rows;
	}

	public function __clone()
	{
		$this->id = null;
		$seats = new ArrayCollection;
		$this->seats->map(function (Seat $seat) use ($seats) {
			$seats->add(clone $seat);
		});
		$this->seats = $seats;
	}

}

src/AppBundle/Controller/Frontend/CryptoPaymentController.php
<?php

namespace AppBundle\Controller\Frontend;

use AppBundle\Entity\Order;
use AppBundle\Service\CryptoPaymentService;
use AppBundle\Service\PaymentService;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class CryptoPaymentController extends Controller
{
    /**
     * Create crypto payment for an order
     * 
     * @Route("/order/{order}/crypto-payment", name="crypto_payment_create")
     */
    public function createCryptoPaymentAction(Order $order, Request $request)
    {
        try {
            // Get the selected cryptocurrency from request (default to BTC)
            $cryptocurrency = $request->get('crypto', 'BTC');
            
            // Validate cryptocurrency
            $allowedCryptos = ['BTC', 'ETH', 'LTC', 'BCH', 'DOGE'];
            if (!in_array($cryptocurrency, $allowedCryptos)) {
                $cryptocurrency = 'BTC';
            }

            /** @var CryptoPaymentService $cryptoPaymentService */
            $cryptoPaymentService = $this->get('service.cryptoPayment');
            
            // Create crypto payment
            $payment = $cryptoPaymentService->createCryptoPaymentForOrder($order, $cryptocurrency);
            
            // Save the payment
            $cryptoPaymentService->savePayment($payment);
            
            // Redirect to the CoinRemitter payment page
            return $this->redirect($payment->getUrl());
            
        } catch (\Exception $e) {
            // Log the error
            $this->get('logger')->error('Crypto payment creation failed: ' . $e->getMessage());
            
            // Add flash message and redirect back to order
            $this->addFlash('error', 'Unable to create crypto payment. Please try again or use card payment.');
            return $this->redirectToRoute('order_detail', ['order' => $order->getId()]);
        }
    }

    /**
     * Handle CoinRemitter webhook notifications
     * 
     * @Route("/crypto-payment/webhook", name="crypto_payment_webhook", methods={"POST"})
     */
    public function webhookAction(Request $request)
    {
        try {
            // Get the webhook data
            $webhookData = json_decode($request->getContent(), true);
            
            if (!$webhookData) {
                return new JsonResponse(['status' => 'error', 'message' => 'Invalid JSON'], 400);
            }

            /** @var CryptoPaymentService $cryptoPaymentService */
            $cryptoPaymentService = $this->get('service.cryptoPayment');
            
            // Process the webhook
            $result = $cryptoPaymentService->processCryptoWebhook($webhookData);
            
            if ($result) {
                return new JsonResponse(['status' => 'success']);
            } else {
                return new JsonResponse(['status' => 'error', 'message' => 'Processing failed'], 400);
            }
            
        } catch (\Exception $e) {
            // Log the error
            $this->get('logger')->error('Crypto webhook processing failed: ' . $e->getMessage());
            return new JsonResponse(['status' => 'error', 'message' => 'Internal error'], 500);
        }
    }

    /**
     * Check crypto payment status (AJAX endpoint)
     * 
     * @Route("/order/{order}/crypto-payment/status", name="crypto_payment_status")
     */
    public function checkPaymentStatusAction(Order $order, Request $request)
    {
        try {
            $payment = $order->getPayment();
            
            if (!$payment || !$payment->isCryptoPayment()) {
                return new JsonResponse(['status' => 'error', 'message' => 'No crypto payment found'], 404);
            }

            $response = [
                'status' => 'pending',
                'paid' => $payment->isPaid(),
                'payment_method' => $payment->getPaymentMethod(),
                'crypto_currency' => $payment->getCryptoCurrency(),
                'invoice_id' => $payment->getCryptoInvoiceId()
            ];

            if ($payment->isPaid()) {
                $response['status'] = 'paid';
                $response['paid_at'] = $payment->getDatetimePaid() ? $payment->getDatetimePaid()->format('Y-m-d H:i:s') : null;
            }

            return new JsonResponse($response);
            
        } catch (\Exception $e) {
            $this->get('logger')->error('Crypto payment status check failed: ' . $e->getMessage());
            return new JsonResponse(['status' => 'error', 'message' => 'Status check failed'], 500);
        }
    }
} 

src/AppBundle/Controller/Frontend/CurrencyController.php
<?php
/**
 * Created by PhpStorm.
 * User: pix
 * Date: 11.08.17
 * Time: 12:03
 */

namespace AppBundle\Controller\Frontend;


use AppBundle\Service\CurrencyService;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Routing\Router;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;

/**
 * @Route(service="controller.frontend.currency")
 */
class CurrencyController
{
	const REFERER = "referer";

	/**
	 * @var CurrencyService
	 */
	private $currencyService;
	/**
	 * @var Router
	 */
	private $router;

	public function __construct(CurrencyService $currencyService,
	                            Router $router)
	{
		$this->currencyService = $currencyService;
		$this->router = $router;
	}

	/**
	 * @Route(path="/switch/currency/{currency}", name="currency_switch")
	 * @param string $currency
	 * @param Request $request
	 * @return
	 */
	public function switchLanguageAction($currency, Request $request)
	{
		$this->currencyService->setCurrentCurrency($currency);

		$router = $request->headers->get(self::REFERER);

		return RedirectResponse::create($router ? $router : $this->router->generate("homepage"));
	}
}

src/AppBundle/Controller/Frontend/LanguageController.php
<?php
/**
 * Created by PhpStorm.
 * User: pix
 * Date: 11.08.17
 * Time: 11:45
 */

namespace AppBundle\Controller\Frontend;


use AppBundle\Entity\Language;
use AppBundle\Service\LanguageService;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Routing\Router;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;

/**
 * @Route(service="controller.frontend.language")
 */
class LanguageController
{
	const REFERER = "referer";

	/**
	 * @var LanguageService
	 */
	private $languageService;
	/**
	 * @var Router
	 */
	private $router;

	public function __construct(LanguageService $languageService,
	                            Router $router)
	{
		$this->languageService = $languageService;
		$this->router = $router;
	}

	/**
	 * @Route(path="/switch/language/{language}", name="language_switch")
	 * @param Language $language
	 * @param Request $request
	 * @return RedirectResponse
	 */
	public function switchLanguageAction(Language $language, Request $request)
	{
		$this->languageService->setCurrentLanguage($language);

		return RedirectResponse::create($request->headers->get(self::REFERER) ?: $this->router->generate("homepage"));
	}
}

src/AppBundle/Resources/views/Frontend/Order/orderDetail.html.twig
{% extends "AppBundle:Frontend/Layout:Skeleton.html.twig" %}

{% block content %}
	<div class="row">
		<div class="col-md-3">
			<div id="left-search" class="left-search-order">
				{{ widget("frontend.searchForm") }}
			</div>
		</div>
		{% if order.cancelled %}
			<div class="col-md-9">
				<div class="row">
					<div class="col-md-7">
						<h2>Rezervace vypršela</h2>
					</div>

				</div>
				<div class="row">
					<div class="col-md-12">
						<p class="alert alert-info">
							Litujeme, ale vaše rezervace vypršela. Pomocí formuláře vlevo si prosím najděte jiný spoj.
							<br>Případně nás kontaktujte na telefonu <strong>+420 724 132 365</strong>,
							nebo napište na <a href="mailto:info@eurotours.cz">info@eurotours.cz</a>.
						</p>
					</div>
				</div>
			</div>
		{% else %}
			<div class="col-md-9">
				<div class="row">
					<div class="col-md-7">
						{% if order.status == "reservation" %}<h2>{{ 'order.thanksReservation'|trans }}</h2>
						{% elseif order.status == "order" %}<h2>{{ 'order.thanksOrder'|trans }}</h2>
						{% elseif order.status == "waitingPay" %}<h2>{{ 'order.paymentOfOrder'|trans }}</h2>
						{% elseif order.status == "expired" %}<h2>{{ 'order.yourOrder'|trans }}</h2>
						{% elseif order.status == "paid" %}<h2>{{ 'order.yourOrder'|trans }}</h2>
						{% endif %}
					</div>
					<div class="col-md-5">
						{% if payment and not payment.paid %}
							<a href="{{ path('order_payment', { order: order.id }) }}" class="btn btn-lg btn-block btn-success" style="margin-top: 10px"><i class="fa fa-credit-card"></i> {{ 'order.payByCard'|trans }}</a>
						{% endif %}
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						{% if order.status == "reservation" %}
							<p class="alert alert-success">{{ 'order.reservationSuccess'|trans }}</p>
						{% elseif order.status == "paid" %}
							<p class="alert alert-success">{{ 'order.paymentSuccess'|trans }} <strong>{{ 'order.ticketsInEmail'|trans }}</strong></p>
						{% endif %}
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<p style="font-size: 1.5em; font-weight: bold; padding: 3px 10px; background-color: #EC02A6; color: white; margin: 15px 0 25px 0">
                            {{ "search.totalPrice"|trans }}: {{ order.priceCurrency|priceCurrency(true, order.priceCurrency.currency) }}

                            {% if order.sellerFee is not null %}
                                ( {{ "order.withSellerFee"|trans }} {{ order.priceWithSellerFeeCurrency|priceCurrency(true, order.priceWithSellerFeeCurrency.currency) }})
                            {% endif %}
                        </p>
					</div>
				</div>
				<div class="row">
					<div class="col-md-7">
						<div class="row order-there">
							<div class="col-md-5">
								<div class="time">{{ order.routeThere.datetimeDeparture|date("j. n. Y H:i") }}</div>
								<div class="city">{{ order.routeThere.simpleFromCityName|language }}</div>
								{% if order.routeThere.fromStation %}
									<div class="station">{{ order.routeThere.fromStation.name|language }}</div>
								{% elseif order.routeThere.fromExternalStation %}
									<div class="station">{{ order.routeThere.fromExternalStation.name|language }}</div>
								{% else %}
									<div class="station">&nbsp;</div>
								{% endif %}
							</div>
							<div class="col-md-1">
								<div class="arrow"><i class="fa fa-arrow-right"></i></div>
							</div>
							<div class="col-md-6">
								<div class="time">{{ order.routeThere.datetimeArrival|date("j. n. Y H:i") }}</div>
								<div class="city">{{ order.routeThere.simpleToCityName|language }}</div>
								{% if order.routeThere.toStation %}
									<div class="station">{{ order.routeThere.toStation.name|language }}</div>
								{% elseif order.routeThere.toExternalStation %}
									<div class="station">{{ order.routeThere.toExternalStation.name|language }}</div>
								{% else %}
									<div class="station">&nbsp;</div>
								{% endif %}
							</div>
						</div>
						{% if order.routeBack %}
							<div class="row order-there">
								<div class="col-md-5">
									<div class="time">{{ order.routeBack.datetimeDeparture|date("j. n. Y H:i") }}</div>
									<div class="city">{{ order.routeBack.simpleFromCityName|language }}</div>
									{% if order.routeBack.fromStation %}
										<div class="station">{{ order.routeBack.fromStation.name|language }}</div>
									{% elseif order.routeBack.fromExternalStation %}
										<div class="station">{{ order.routeBack.fromExternalStation.name|language }}</div>
									{% else %}
										<div class="station">&nbsp;</div>
									{% endif %}
								</div>
								<div class="col-md-1">
									<div class="arrow"><i class="fa fa-arrow-right"></i></div>
								</div>
								<div class="col-md-6">
									<div class="time">{{ order.routeBack.datetimeArrival|date("j. n. Y H:i") }}</div>
									<div class="city">{{ order.routeBack.simpleToCityName|language }}</div>
									{% if order.routeBack.toStation %}
										<div class="station">{{ order.routeBack.toStation.name|language }}</div>
									{% elseif order.routeBack.toExternalStation %}
										<div class="station">{{ order.routeBack.toExternalStation.name|language }}</div>
									{% else %}
										<div class="station">&nbsp;</div>
									{% endif %}
								</div>
							</div>
						{% endif %}
					</div>
					<div class="col-md-5">
						<ul class="list-group">
							{% for orderPerson in order.orderPersons %}
								<li class="list-group-item">
									<h4>{{ orderPerson.name }}</h4>
									<p><strong>{{ "order.phone"|trans }}:</strong> {{ orderPerson.phone }}</p>
									<p><strong>{{ 'order.price'|trans }}:</strong> {{ orderPerson.routeTariffThere.priceCurrencyIncludeSurcharge|priceCurrency(true, orderPerson.routeTariffThere.priceCurrency.currency) }}</p>
								</li>
							{% endfor %}
						</ul>
					</div>
				</div>
			</div>
		{% endif %}
	</div>
{% endblock %}